from dotenv import load_dotenv

load_dotenv()

REFRESH_TOKEN = "REFRESH_TOKEN"
LWA_APP_ID = "LWA_APP_ID"
CLIENT_SECRET = "CLIENT_SECRET"
AWS_ACCESS_KEY = "AWS_ACCESS_KEY"
AWS_SECRET_KEY = "AWS_SECRET_KEY"
ROLE_ARN = "ROLE_ARN"
